Edit .gitlab-ci.yml

diff --git a/GitOps/.gitlab-ci.yml b/GitOps/.gitlab-ci.yml
--- a/GitOps/.gitlab-ci.yml
+++ b/GitOps/.gitlab-ci.yml
@@ -8,10 +8,10 @@ verify_tags:
     - echo "FRONTEND_TAG Recived: $FRONTEND_DOCKER_TAG"
     - echo "BACKEND_TAG Recived: $BACKEND_DOCKER_TAG"
     - |
-        if [ -z "$FRONTEND_DOCKER_TAG" ] || [ -z "$BACKEND_DOCKER_TAG" ]; then
-          echo "One or more required tags are missing"
-          exit 1
-        fi 
+      if [ -z "$FRONTEND_DOCKER_TAG" ] || [ -z "$BACKEND_DOCKER_TAG" ]; then
+        echo "One or more required tags are missing"
+        exit 1
+      fi 
 
 update_manifests:
   stage: update
