Edit .gitlab-ci.yml

diff --git a/GitOps/.gitlab-ci.yml b/GitOps/.gitlab-ci.yml
--- a/GitOps/.gitlab-ci.yml
+++ b/GitOps/.gitlab-ci.yml
@@ -5,12 +5,13 @@ stages:
 verify_tags:
   stage: verify
   script:
-    - set -e
     - echo "FRONTEND_TAG Recived: $FRONTEND_DOCKER_TAG"
     - echo "BACKEND_TAG Recived: $BACKEND_DOCKER_TAG"
     - |
-        [ -n "$FRONTEND_DOCKER_TAG" ] || { echo "Missing FRONTEND_DOCKER_TAG"; exit 1; }
-        [ -n "$BACKEND_DOCKER_TAG" ] || { echo "Missing BACKEND_DOCKER_TAG"; exit 1; } 
+        if [ -z "$FRONTEND_DOCKER_TAG" ] || [ -z "$BACKEND_DOCKER_TAG" ]; then
+          echo "One or more required tags are missing"
+          exit 1
+        fi 
 
 update_manifests:
   stage: update
